### ISSUE TITLE
What does the prometheus value mean?

### ISSUE THREAD

**Issue by benmathews** [yuriipolishchuk/componentstatuses-exporter#2]
You say `Don't forget to update prometheus parameter value in values.yaml.`. Nowhere does it say what this means.  Why would the exporter need to know where prometheus is?

**Comment by yuriipolishchuk** [comment]
@benmathews On the project I work for we use [prometheus-operator](https://github.com/coreos/prometheus-operator) which introduces ServiceMonitor k8s CRD  to select the service objects to be monitored by the Prometheus server. 

The helm chart in this repo deploys the ServiceMonitor to automate things a bit.

Maybe it's a good idea to deploy it when it's required only.

**Comment by benmathews** [comment]
With that explanation, this is really a duplicate of #3.
