### ISSUE TITLE
Only support for prometheus operator?

### ISSUE THREAD

**Issue by benmathews** [yuriipolishchuk/componentstatuses-exporter#3]
I see that this includes a service monitor definition. But doesn't define an annotation. Is this to only be used for installations with the prometheus operator?

**Comment by yuriipolishchuk** [comment]
@benmathews
Well, I think I can make it more flexible

**Comment by benmathews** [comment]
That would be great. We expect an annotation of `prometheus.io/scrape` on our service for prometheus to pick it up.

**Comment by yuriipolishchuk** [comment]
@benmathews done. Please uncomment annotations [here](https://github.com/yuriipolishchuk/kube-componentstatuses-prometheus-exporter/blob/master/helm/values.yaml#L12-L15). 

I've tested it with helm-deployed prometheus. Seems to be working.

**Comment by benmathews** [comment]
Thanks for the fast work. I'll give it a try tomorrow.
